### ISSUE TITLE
7.4.4

### ISSUE THREAD

**Issue by leegel** [rrrrrrri/fgt-gadgets#18]
![image](https://github.com/user-attachments/assets/f81b826f-7085-47f9-a29c-5202af0dd095)

[*] Unpacking kernel
[-] flatkc is not a valid kernel file

**Comment by rrrrrrri** [comment]
7.4.4 has not been tested.

**Comment by leegel** [comment]
![image](https://github.com/user-attachments/assets/2a21f23d-a660-417d-9f17-7ce972172083)
7.4.2 and 7.4.3 same tips,It's really strange

**Comment by rrrrrrri** [comment]
Try to run this command: vmlinux-to-elf flatkc flatkc.elf

**Comment by leegel** [comment]
[*] Unpacking kernel
[*] Do analyse
[+] Cache saved to ./00c04a0450679d5415d874c5bdc8d1c9
Traceback (most recent call last):
  File "decrypt.py", line 230, in <module>
    decrypt(kernel, enc_data)
  File "decrypt.py", line 171, in decrypt
    mu.mem_map(init_data_seg_addr, pad_size(init_data_seg_size))  # map .init.data
  File "/usr/local/lib/python3.8/dist-packages/unicorn/unicorn.py", line 621, in mem_map
    raise UcError(status)
unicorn.unicorn.UcError: Invalid memory mapping (UC_ERR_MAP)

**Comment by rrrrrrri** [comment]
The offset may differ from version to version, you can try to debug the script and see what init_data_seg_addr is, or you can try to use https://github.com/optistream/fortigate-crypto

**Comment by kv142** [comment]
Hi all. Someone was able to make an Unpacking kernel according to the instructions?
 Also for me **flatkc is not a valid kernel file**

**Comment by Rapici** [comment]
Hi @kv142 
I tried but not working fine :( my mistake

**Comment by kv142** [comment]
I solved this quest.
But there are many restrictions:
1) The instructions only work on version 7.4.3 and do not work on 7.4.4 (maybe if you fix the scripts it will work on 7.4.4)
2) After each reboot, network interfaces must be rewritten IP addresses
3) When booting, the system constantly writes that the disk system is inconsistent and a disk check needs to be done.
4) The serial number that we generate is not registered on the vendor’s website and, accordingly, we cannot update any databases.
Conclusion: a) yes, the hack works on 7.4.3
                   b) it cannot be used in an industrial network, only for training purposes.
![11](https://github.com/user-attachments/assets/975af935-01f4-40c5-b5ff-82e4a712bb55)
![22](https://github.com/user-attachments/assets/7023ec71-953f-463a-9814-7bf3cd570d9d)
![44](https://github.com/user-attachments/assets/9ede40c7-7f47-462f-9a00-cdc5bb435f62)

**Comment by ProTechEx** [comment]
PLEASE UPDATE IT FOR THE LATEST FGT_VM64-v7.6.0

**Comment by paulierco** [comment]
@kv142  it depends on the serial numbers, they actually reflect the license.

**Comment by maherrich** [comment]
Does any one have a serial that is not expired

**Comment by Rapici** [comment]
Hi @maherrich only I have for 7.4.1 version
newer versions doesn't work correctly for me 7.4.2 or 7.4.4 or last version 7.4.6
I hope that @rrrrrrri  or @kv142 could be find it some solution

Regards
Rapici

**Comment by caiiicv** [comment]
> 我解决了这个任务。 但是有很多限制：
> 
> 1. 该说明仅适用于版本 7.4.3，不适用于 7.4.4（也许如果你修复脚本它将适用于 7.4.4）
> 2. 每次重启后，网络接口必须重写IP地址
> 3. 在启动的时候系统不断的写磁盘系统不一致，需要做磁盘检查。
> 4. 我们生成的序列号未在供应商的网站上注册，因此我们无法更新任何数据库。
>    结论：a) 是的，该黑客程序在 7.4.3 上有效
>    b) 它不能用于工业网络，只能用于培训目的。
>    ![11](https://private-user-images.githubusercontent.com/181000481/365992897-975af935-01f4-40c5-b5ff-82e4a712bb55.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTY0NDQsIm5iZiI6MTczMzA1NjE0NCwicGF0aCI6Ii8xODEwMDA0ODEvMzY1OTkyODk3LTk3NWFmOTM1LTAxZjQtNDBjNS1iNWZmLTgyZTRhNzEyYmI1NS5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjI5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZGJhOGM2ZTRjOWY1NzRiNTJmN2M2MDQ4MGI2NTc2OTI4YjE0NmQ2ZGRhMjY1MjkyZTkwOGY4MGU5OTg1Mzc3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0zUpNjWcFZrImK9bZCMuVbDGLIgf4kQaQlf-TseeWXA)
>    ![22](https://private-user-images.githubusercontent.com/181000481/365993288-7023ec71-953f-463a-9814-7bf3cd570d9d.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTY0NDQsIm5iZiI6MTczMzA1NjE0NCwicGF0aCI6Ii8xODEwMDA0ODEvMzY1OTkzMjg4LTcwMjNlYzcxLTk1M2YtNDYzYS05ODE0LTdiZjNjZDU3MGQ5ZC5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjI5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWUzYTQyOGMxZTllYzVlMjYzNTk4MWM4NzA5MTJiM2FlODNmZTNkMjFjMmQzNDhlYjQ5MjI3NDNlZDk0MmFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cyy9xnIdSZCKzVeIxH7_VRGnb0SnYzQDQop4Ls-5NHs)
>    ![四十四](https://private-user-images.githubusercontent.com/181000481/365993820-9ede40c7-7f47-462f-9a00-cdc5bb435f62.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTY0NDQsIm5iZiI6MTczMzA1NjE0NCwicGF0aCI6Ii8xODEwMDA0ODEvMzY1OTkzODIwLTllZGU0MGM3LTdmNDctNDYyZi05YTAwLWNkYzViYjQzNWY2Mi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjI5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZGQ3ODIxYjk0NTljNzE2MDdmMWI3NTFjNTUyYTgxNmUzYTYzNTU1YmRhYmMzOTdmNGE2MjRjZDU4ZDNhMTU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kaOnWbJpuLokCtpnvBBPtYFnHxPU0EVbdxkKpkG0MCs)
>    ![55](https://private-user-images.githubusercontent.com/181000481/365995797-c520288a-45da-48d7-9ea5-9828353c21c6.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNTY0NDQsIm5iZiI6MTczMzA1NjE0NCwicGF0aCI6Ii8xODEwMDA0ODEvMzY1OTk1Nzk3LWM1MjAyODhhLTQ1ZGEtNDhkNy05ZWE1LTk4MjgzNTNjMjFjNi5KUEc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxMjI5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZDc1NDM1MGM3MGYyZTEzYjJlNWJhMzk2MGJmOGMzMGQ1ODNiYjNiMTk5Yjg2NGE3OGI0NjEyNmI3NDg2NDFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JR769Zpj9TrRQOngDGHpaOanSouh-NzUigDJ-Pk59pU)

I also encountered the same situation as you, many functions are restricted, I hope that the program can be updated to fix this problem. I tested FortiGate-VM7.4.4 and failed to decrypt rootfs. The program is not suitable for this version.

**Comment by bogdanovr** [comment]
Some research from akamai on new encryption algorithm starting v.7.4.4:
https://www.akamai.com/blog/security-research/2025-february-fortinet-critical-vulnerabilities

**Comment by Rapici** [comment]
Hi @bogdanovr it's seem interested https://www.akamai.com/blog/security-research/2025-february-fortinet-critical-vulnerabilities
Good job! I hope that somebody will try ;)

Regards
